#!/bin/sh

#Add node modules to PATH
PATH=$PATH:/usr/local/bin:/usr/local/sbin

git stash -q --keep-index

#Run test
cd app/test
mocha-phantomjs ./index.html
RETVAL=$?
cd ../../

git stash pop -q

if [ $RETVAL -ne 0 ]
then
  exit 1
fi
