#!/bin/sh

#Add node modules to PATH
PATH=$PATH:/usr/local/bin:/usr/local/sbin

#Minimize CSS
cd app/css
cleancss --skip-rebase -o sharingear.min.css sharingear.css

#Build app
cd ../js
webpack --optimize-minimize

#Build test
cd ../test/js
webpack --optimize-minimize

#Stage build
cd ../../../
git add --refresh
git add .

git stash -q --keep-index

#Run test
cd app/test
mocha-phantomjs ./index.html
RETVAL=$?
cd ../../

git stash pop -q

if [ $RETVAL -ne 0 ]
then
  exit 1
fi
