#!/bin/sh

# @args --no-optimize: Do not optimize JS 
# @args --no-test: Skip building the tests

optimizeFlag="--optimize-minimize"
noTest=true

while [ "$1" != "" ]; do
	case $1 in
		--no-optimize )	optimizeFlag=
						;;
		--no-test ) noTest=false
					;;
	esac
	shift
done


#Add node modules to PATH
PATH=$PATH:/usr/local/bin:/usr/local/sbin

#Minimize CSS
cd ../app/css
cleancss --skip-rebase -o sharingear.min.css sharingear.css

echo "CSS minimized..."

#Build app
cd ../js
webpack $optimizeFlag --progress

echo "App built..."

if [ "$noTest" == true ]; then
	#Build test
	cd ../test/js
	webpack $optimizeFlag --progress
	echo "Tests built..."
fi

echo "Done."
