#!/bin/sh

#Add node modules to PATH
PATH=$PATH:/usr/local/bin:/usr/local/sbin

#Minimize CSS
cd ../app/css
cleancss --skip-rebase -o sharingear.min.css sharingear.css

#Build app
cd ../js
webpack --optimize-minimize --progress

#Build test
cd ../test/js
webpack --optimize-minimize --progress